from django.urls import path
from . import views

app_name = "main"

urlpatterns = [ 
    path('', views.welcome_view, name="welcome"),
    path('shop', views.shop_view, name="shop"),
    path('shopfilter/', views.shop_filter_view, name="shopfilter"),
    path('exshopfilter/<str:filter>', views.ex_shop_filter_view, name="exshopfilter"),
    path('fabrics', views.fabrics_view, name="fabrics"),
    path('fabricsfilter/', views.fabrics_filter_view, name="fabricsfilter"),
    path('exfabricsfilter/<str:filter>', views.ex_fabrics_filter_view, name="exfabricsfilter"),
    path('addfabric', views.add_fabric_view, name="add_fabric"),
    path('addcloth', views.add_cloth_view, name="add_cloth"),
    path('tailors', views.tailors_list_view, name="tailors_list"),
    path('cloth_sample/<int:cloth_id>', views.cloth_sample_view, name="cloth_sample"),
    path('fabric_sample/<int:fabric_id>', views.fabric_sample_view, name="fabric_sample"),
    # path('mail/<int:cloth_id>', views.mail_view, name="sendmail"),
    path('profile/<int:partner_id>', views.external_profile_view, name="profile"),
    path('custProfile/<int:customer_id>', views.customer_profile_view, name="custProfile"),
    path('custProfileImage/', views.customer_profile_image_view, name="custProfileImage"),
    path('editCustProfile<int:customer_id>', views.edit_customer_view, name="editCustProfile"),
    path('partnerProfile/<int:partner_id>', views.partner_profile_view, name="partnerProfile"),
    path('editPartnerProfile<int:partner_id>', views.edit_partner_view, name="editPartnerProfile"),
    path('partner_reg', views.partner_reg_view, name="partner_reg"),
    path('partner', views.partner_view, name="partner"),
    path('request_submitted', views.success_reg_view, name="request_submitted"),
    path('add_partner/<int:partner_id>', views.add_partner_view, name="add_partner"),
    path('measureopt', views.measureopt_view, name="measureopt"),
    path('measuredetails', views.measuredetails_view, name="measuredetails"),
    path('measurehowto', views.measurehowto_view, name="measurehowto"),
    path('promeasure', views.promeasure_view, name="promeasure"),
    path('changepass', views.change_user_pass, name="changepass"),
    path('newaddress', views.newaddress_view, name="newaddress"),
    path('editaddress/<int:address_id>', views.edit_address_view, name="editaddress"),
    path('cart', views.cart_view, name="cart"),
    path('changeaddress/<int:address_id>', views.change_address_view, name="changeaddress"),
    path('updatespecs', views.update_specs_view, name="updatespecs"),

    path('updatemeasurementdetails', views.update_measurement_view, name='updatemeasurementdetails'),
    path('search/<str:query>', views.search_view, name='search'),

    path('popauth', views.popauth_view, name="popauth"),
    path('auth', views.auth_view, name="auth"),
    path('login', views.login_view, name="login"),
    path('login2', views.poplogin_view, name="login2"),
    path('register', views.register_view, name="register"),
    path('register2', views.popregister_view, name="register2"),
    path('logout', views.logout_view, name="logout"),
    #path('index', views.home_view, name="home"),
]
