# Generated by Django 2.1 on 2022-01-25 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Baby'), ('T', 'Traditional'), ('O', 'Modern'), ('C', 'Classic')], default='M', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(upload_to=main.models.cloth_image_path)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('gen_size', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(null=True)),
                ('gender_spec', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Baby'), ('T', 'Traditional'), ('O', 'Modern'), ('C', 'Classic')], default='M', max_length=6)),
                ('location', models.TextField(null=True)),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=3)),
                ('profile_image', models.ImageField(default='Tailor_12/profile_image/images/blank-profile-picture-gc048af202_1280.png', upload_to=main.models.tailor_profile_path)),
                ('background_image', models.ImageField(default='Tailor_12/background_image/images/paper-g0b57e8602_1920.jpg', upload_to=main.models.tailor_background_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
