# Generated by Django 4.0.1 on 2022-03-06 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSellerReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('business_name', models.CharField(max_length=225)),
                ('ig_link', models.CharField(max_length=225, null=True)),
                ('what_i_do', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('zipcode', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingTailorReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('business_name', models.CharField(max_length=225)),
                ('ig_link', models.CharField(max_length=225, null=True)),
                ('what_i_do', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('zipcode', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225, null=True)),
                ('last_name', models.CharField(max_length=225, null=True)),
                ('phone_no1', models.CharField(max_length=15, null=True)),
                ('phone_no2', models.CharField(max_length=15, null=True)),
                ('gender_spec', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Baby'), ('T', 'Traditional'), ('O', 'Modern'), ('C', 'Classic')], default='M', max_length=6)),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=3)),
                ('profile_image', models.ImageField(default='Tailor_12/profile_image/images/blank-profile-picture-gc048af202_1280.png', upload_to=main.models.tailor_profile_path)),
                ('background_image', models.ImageField(default='Tailor_12/background_image/images/paper-g0b57e8602_1920.jpg', upload_to=main.models.tailor_background_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225, null=True)),
                ('last_name', models.CharField(max_length=225, null=True)),
                ('phone_no1', models.CharField(max_length=15, null=True)),
                ('phone_no2', models.CharField(max_length=15, null=True)),
                ('spec', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Baby'), ('T', 'Traditional'), ('O', 'Modern'), ('C', 'Classic')], default='M', max_length=6)),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Not specified', max_length=225)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to=main.models.fabrics_image_path)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no1', models.CharField(max_length=15, null=True)),
                ('phone_no2', models.CharField(max_length=15, null=True)),
                ('gen_size', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Baby'), ('T', 'Traditional'), ('O', 'Modern'), ('C', 'Classic')], default='M', max_length=3)),
                ('price', models.IntegerField(default=1000, null=True)),
                ('image', models.ImageField(upload_to=main.models.cloth_image_path)),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=3)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('zipcode', models.CharField(max_length=225, null=True)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
