# Generated by Django 4.0.1 on 2022-03-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clothe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='type',
            field=models.IntegerField(choices=[(1, 'Ankara'), (2, 'Aso Oke'), (3, 'Atiku'), (4, 'Adire'), (5, 'Brocades'), (6, 'Chiffon'), (7, 'Lace'), (8, 'Silk'), (9, 'Tulle'), (10, 'Velvet')], default=1),
        ),
    ]
