# Generated by Django 4.0.1 on 2022-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_fabric_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='type',
            field=models.CharField(choices=[('K', 'Ankara'), ('A', 'Adire'), ('O', 'Aso Oke'), ('T', 'Atiku'), ('B', 'Brocades'), ('C', 'Chiffon'), ('L', 'Lace'), ('S', 'Silk'), ('T', 'Tulle'), ('V', 'Velvet')], default='K', max_length=1),
        ),
    ]
