# Generated by Django 4.0.1 on 2022-02-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_phone_no_customer_phone_no1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no1',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no2',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
