# Generated by Django 4.0.1 on 2022-02-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customer_phone_no1_alter_customer_phone_no2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.TextField(null=True),
        ),
    ]
