# Generated by Django 4.0.1 on 2022-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_customer_address_remove_customer_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailor',
            old_name='location',
            new_name='phone_no1',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='tailor',
            name='phone_no2',
            field=models.TextField(null=True),
        ),
    ]
