# Generated by Django 4.0.1 on 2022-02-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pendingsellerreg_pendingtailorreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='city',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='company_name',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='first_name',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='last_name',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='state',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='zipcode',
            field=models.TextField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='city',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='company_name',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='first_name',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='last_name',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='state',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='zipcode',
            field=models.TextField(max_length=225, null=True),
        ),
    ]
