# Generated by Django 4.0.1 on 2022-02-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_pendingsellerreg_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no2',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='address',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='city',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='company_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='first_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='last_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='state',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='zipcode',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='address',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='city',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='company_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='first_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='last_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='state',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='zipcode',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_no1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_no2',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='phone_no1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='phone_no2',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
