# Generated by Django 4.0.1 on 2022-02-24 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsellerreg',
            name='business_name',
            field=models.CharField(default=datetime.datetime(2022, 2, 24, 18, 32, 39, 317779, tzinfo=utc), max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingsellerreg',
            name='ig_link',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pendingsellerreg',
            name='what_i_do',
            field=models.CharField(default=datetime.datetime(2022, 2, 24, 18, 32, 45, 771970, tzinfo=utc), max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingtailorreg',
            name='business_name',
            field=models.CharField(default=datetime.datetime(2022, 2, 24, 18, 33, 9, 545431, tzinfo=utc), max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingtailorreg',
            name='ig_link',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pendingtailorreg',
            name='what_i_do',
            field=models.CharField(default=datetime.datetime(2022, 2, 24, 18, 33, 14, 835880, tzinfo=utc), max_length=225),
            preserve_default=False,
        ),
    ]
