# Generated by Django 4.0.1 on 2022-02-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pendingsellerreg_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingsellerreg',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='pendingtailorreg',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='ig_link',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='pendingsellerreg',
            name='what_i_do',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='ig_link',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='pendingtailorreg',
            name='what_i_do',
            field=models.TextField(),
        ),
    ]
