# Generated by Django 4.0.1 on 2022-02-26 02:11

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_pendingsellerreg_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='first_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='first_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='last_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.CreateModel(
            name='Fabrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Not specified', max_length=225)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(upload_to=main.models.fabrics_image_path)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seller')),
            ],
        ),
    ]
