# Generated by Django 4.0.1 on 2022-02-27 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_seller_first_name_seller_last_name_tailor_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothe',
            name='price',
        ),
        migrations.AddField(
            model_name='clothe',
            name='price_range',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
