# Generated by Django 4.0.1 on 2022-02-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_clothe_price_clothe_price_range'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fabrics',
            new_name='Fabric',
        ),
    ]
