# Generated by Django 4.0.1 on 2022-02-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_fabrics_fabric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='price',
            field=models.CharField(max_length=225),
        ),
    ]
