# Generated by Django 4.0.1 on 2022-03-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_fabric_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=3),
        ),
    ]
