# Generated by Django 4.0.1 on 2022-03-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_clothe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='price',
            field=models.IntegerField(),
        ),
    ]
